[project]
name = "docs-kth-rdm"
version = "0.1.0"
description = "KTH Data Repository documentation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-glightbox>=0.5.2",
    "mkdocs-material>=9.6.22",
    "mkdocs-static-i18n>=1.2.3",
]
